services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672" # RabbitMQ Standard-Port
      - "15672:15672" # RabbitMQ Management-Port
    volumes:
      - ./rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - local_network

volumes:
  rabbitmq_volume:
    driver: local

networks:
  local_network:
    driver: bridge
